### ISSUE TITLE
Can't complete configuration of Twitch Extension

### ISSUE THREAD

**Issue by PierfrancescoDamiani** [GoryMoon/StreamEngineer#3]
So, I've installed the extension Stream Manipulations but it keeps telling me that it needs configuration. I've added some actions but it keeps asking for configuration. Copied and pasted the token.
This way i can't activate the extension and use it in the overlay.

![image](https://user-images.githubusercontent.com/32416483/75989471-9d755e00-5ef3-11ea-9e37-50d9726102b4.png)

**Comment by GoryMoon** [comment]
I've identified the issue and working on fixing it now.
You can get it working before my fix by loading the game with the plugin and it should be fixed.
This is only an issue for new accounts  and should not happen for you in the future.

**Comment by GoryMoon** [comment]
I've manually fixed your settings so it should work now.

**Comment by GoryMoon** [comment]
Fixed by https://github.com/GoryMoon/StreamManipulationsExtension/commit/8030657a1dce506aaa66f384dc870496f106f660

**Comment by PierfrancescoDamiani** [comment]
Wow! So fast! Thanks, now it works!

**Comment by PierfrancescoDamiani** [comment]
Hello and thanks for the fast reply!

Can I ask you more help?
I don't know if its an issue or isn't still fully developed or I'm a noob,
but i can't understand how to make channel points rewards work.
From the twitch extension it seems you can't add actions with channel
points, but only with bits.
And in the "events.json" file i can't understand where i have to find the
"channel_point_id" field.
From the provided URL  https://smapi.gorymoon.se/dashboard/chat  i don't
find any usable setting for channel points. The only thing i find is to let
the bot join/leave chat, but it seems there's no bot joining.

[image: image.png]

Let me know if i can provide more information and thank you in advance for
the support and help
This plugin seems very cool and i look forward to see it in action

Pierfrancesco


Il giorno gio 5 mar 2020 alle ore 16:13 Gustaf Järgren <
notifications@github.com> ha scritto:

**Comment by GoryMoon** [comment]
The channel points are only available inside the `events.json`, you go to the dashboard and have the bot join the chat, it won't show in the list, then run a channel point reward and it will show on the dashboard.
You use the id from that and add it to an action in the `events.json` file.
The `events.json` will hold actions for cheers, subs and channel points.

**Comment by PierfrancescoDamiani** [comment]
Thanks for the reply,

I've already tested some channel point rewards, but doesn't apper anything
in the page, as you can see in the screenshot. Maybe I have to set specific
settings for the reward in order to appear in the list?

Pierfrancesco

Il giorno gio 5 mar 2020 alle ore 20:09 Gustaf Järgren <
notifications@github.com> ha scritto:

**Comment by GoryMoon** [comment]
The screenshot wan't included in the reply to github, it only say `[image: image.png]`.
The channel point reward must require user input.

**Comment by PierfrancescoDamiani** [comment]
Ok, so i've tested with a custom channel points reward that require user
input. But still doesn't appear anything in the list.


Il giorno ven 6 mar 2020 alle ore 00:34 Gustaf Järgren <
notifications@github.com> ha scritto:
