### ISSUE TITLE
[FEATURE REQUEST] Optional of using Twitch Points over Bits

### ISSUE THREAD

**Issue by willkillyaquick** [GoryMoon/StreamEngineer#5]
Would like to have the option to choose either Twitch Points or Bits when configuring the extension's Actions.

**Comment by GoryMoon** [comment]
Under [README#conditions](https://github.com/GoryMoon/StreamEngineer/blob/1.19/GoryMoon.StreamEngineer/README.md#conditions) you can find info on how to use channel points.
